### ISSUE TITLE
Combat-Tag on offensive potion use and affect

### ISSUE THREAD

**Issue by erocs** [Civcraft/Humbug#10]
https://www.reddit.com/r/Civcraft/comments/2x3wi1/morning_changelog_20150225/cown2wr

When offensive potions are thrown or initially damage/affect an individual, CombatTag them.

**Comment by jjj5311** [comment]
Do you think this is something that might be able to go into the Combat-Tag main repo with config?

**Comment by rourke750** [comment]
@jjj5311 Certainly possible.  I got some prisonpearl changes that were in our custom combat tag into the main repo.

**Comment by TealNerd** [comment]
Potions already do this (or at least harming potions do) in any case this should be in combat tag not humbug

**Comment by suirad** [comment]
This should probably be closed then.
