### ISSUE TITLE
Item dup with loot_multiplier

### ISSUE THREAD

**Issue by erocs** [Civcraft/Humbug#11]
If a mob picks up a weapon, the loot_multiplier will duplicate that item when the mob dies.

**Comment by erocs** [comment]
So this can't use a hard coded list of what the mobs drop as anything they drop could be dup'd.

Bukkit doesn't have events for a mob picking up items. On EntityDeathEvent, get EntityDeathEvent.getEntity(), check if LivingEntity.getCanPickupItems() is true, and then clear out of EntityDeathEvent.getDrops() everything listed as being in a LivingEntity.getEquipment() slot.

**Comment by jjj5311** [comment]
reason we don't let loot multiply in the end?

https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L833

**Comment by jjj5311** [comment]
Also i have no idea performance wise but should we disable all exp orbs from being dropped since they are not useful

**Comment by rourke750** [comment]
It was to stop endermen from increasing payout.  This was coded very early 2.0 where endermen spawned but other mobs did not.  Did not want to double the output of endermen from 2db of pearls to 4 a day but now it is no longer needed.

**Comment by rourke750** [comment]
I dont believe you can stop them from being dropped.

**Comment by jjj5311** [comment]
yeah i was looking through the methods and there is a way to disable xp orbs... i should be able to work on this tonight or tomorrow

**Comment by jjj5311** [comment]
do we want to allow loot duplication on armor/swords/items they spawn with?

**Comment by jjj5311** [comment]
i didnt think those items should be duplicated plus that way we dont have to handle mobs that can pick up items differently

#12

**Comment by WildWeazel** [comment]
To test:
Spawn some undead mobs and get them to pick up items they wouldn't spawn with, especially armor and weapons. This may take some trial and error since not all mobs have the ability.
Kill them all
Verify that they dropped extra normal items, but no more of your items than they picked up.

**Comment by Xavter** [comment]
Just tested it with pigmen, it worked. To get pigmen to pickup items, attack them with an inventory full of chain mail and diamond swords and have them kill you, go back to them and some will have picked up the items. They will consistently drop only one of the type of weapon/armor they had picked up.

I also just made a commit and optimized/comment code a bit.

**Comment by rourke750** [comment]
The only issue I can think of is that they arent meant to 100 percent of
the time return all items.

**Comment by jjj5311** [comment]
they will not always drop armor if they spawn with it, however if they pick
something up in vanilla i believe they always drop whatever they picked up.

When i was testing this locally the mobs that spawn with armor (i tested
with zombies) they did not always drop the armor they spawned with, it must
be stored in a different location

**Comment by Xavter** [comment]
The drop rate on weapons/armor they spawned with is consistent with their other items, and there's a 100% drop rate on ones they have picked up. I think the mechanics are right since if pigmen dropped gold swords every time they died then portal farms would be overloaded with them. We shouldn't need to look where their natural weapons/armor are stored because it's already perfect.

**Comment by WildWeazel** [comment]
Is the vanilla drop rate related to whether they spawn with a sword?

**Comment by ttk2** [comment]
that's a really good question Travis, does anyone know? We want to be sure
this isn't modifying anything, also is this on Civtest? Otherwise good work
everyone and we should be able to get this online soon.

**Comment by WildWeazel** [comment]
According to the wiki equipment only drops occasionally if it's actually worn by the mob, so with this rule spawned equipment would not multiply. I don't think that's really a problem though since those items aren't generally what people are grinding for.

**Comment by ttk2** [comment]
what would multiply then?

**Comment by jjj5311** [comment]
It just needs to be tested. In theory none only their "drops" that they are
not holding when they live would duplicate

**Comment by WildWeazel** [comment]
Anything that's randomly generated at the time of death should multiply, but not what they're wearing. I just wasn't sure if their random sword/armor drops were independent of what's visibly equipped, and apparently it is not. But yeah, this is all based on the wiki so further testing is good.

**Comment by ttk2** [comment]
is this on Civtest yest?

**Comment by ttk2** [comment]
yet*

**Comment by jjj5311** [comment]
I believe you put it on their and it's in testing

**Comment by jjj5311** [comment]
what is the final testing this needs? the only thing i would change is to re-instate the end duplication i removed if enderman will be back to normal

**Comment by ttk2** [comment]
I think so, I just need confirmation it works as it should for all mobs.

**Comment by GavJenks** [comment]
Why am I ever getting an odd number of loot items on civtest right now if it's supposed to be doubling drops?

**Comment by jjj5311** [comment]
I don't think this actually made it to civtest

**Comment by erocs** [comment]
CivTest wasn't configured. "humbug loot_multiplier generic 2" run and saved.

**Comment by ttk2** [comment]
I was sure I had done that.

**Comment by WildWeazel** [comment]
Is this live yet?

**Comment by jjj5311** [comment]
yes, loot_multiplier is still set at 1 though

**Comment by jjj5311** [comment]
can this be closed as well?

**Comment by ttk2** [comment]
I think so
