### ISSUE TITLE
Strengh reverting during fights

### ISSUE THREAD

**Issue by jjj5311** [Civcraft/Humbug#13]
Look all over the subreddit to see this issue being talked about

https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1487-L1512

I think this has to be where the issue is as it is the only thing dealing with damage dealt, could also be in the armor section as well

https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1061-L1105

I don't see anything blatantly obvious here

**Comment by ttk2** [comment]
If its as occasional as it is described then I think it might be spigot not
us

**Comment by TealNerd** [comment]
I figured this out and we can't do anything about it. When the tick is really bad the EntityDamageByEntityEvent fucks up and doesn't get fired

**Comment by ttk2** [comment]
I figured it was a bukkit think. How did you determine it?

**Comment by TealNerd** [comment]
I was testing another plugin that uses the event and when the tick dropped on my testing server the event wasn't always firing

**Comment by jjj5311** [comment]
i think this one can be closed then?

**Comment by ttk2** [comment]
Its still an issue. We just can't do anything about it.

**Comment by suirad** [comment]
Should be labeled as such

**Comment by ttk2** [comment]
wontfix?

**Comment by suirad** [comment]
Yea that sounds good. If its something that is affected by lag and/or bukkit, it doesn't leave much room to play with it. A wontfix/bukkit-issue label and a close would suffice.

**Comment by suirad** [comment]
Please close and lable wontfix
