### ISSUE TITLE
Naming a book the same title as the spawn book will prevent it from dropping upon death

### ISSUE THREAD

**Issue by drjawa** [Civcraft/Humbug#17]
Haven't tested this on the server itself as it was reported to us.

Name the book the same title as the newbie book.

https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1236

Suggested fix was to compare against author name as that can't be modified.

**Comment by ttk2** [comment]
agreed, this is a nice to have (unless enchanted books can be gimmicked in
this way but I think not

**Comment by TealNerd** [comment]
Enchanted books and signed books are two different items so it shouldn't be a problem

**Comment by jjj5311** [comment]
How are they naming with a name that long? standard book and quill can only be 16 characters?

**Comment by ttk2** [comment]
Thats a goof question. Has anyone tried on civtest?

**Comment by jjj5311** [comment]
I cannot make this happen on civtest

**Comment by TealNerd** [comment]
Again this shouldn't be an issue since you could only dupe a book with the
same title and books are cheap anyway I would be easier to just make books

**Comment by drjawa** [comment]
WildWeazel committed a fix here: https://github.com/Civcraft/Humbug/commit/a791d0246d96cf6280a18bed07f3eabca7dfbf1f
