### ISSUE TITLE
Reduce pigman spawn rate, multiply mob drops by 9

### ISSUE THREAD

**Issue by Xavter** [Civcraft/Humbug#19]
As discussed on the sub, we edit humbug code and add a new config setting to edit default pigman spawn rates, and make portal spawn rates happen and do some slight editing to the loot multiplier code to make the multiplier the same as the reduction in spawn rate.
http://www.reddit.com/r/Civcraft/comments/308skt/morning_changelog_20150325/cpq5okg

**Comment by jjj5311** [comment]
I don't think we currently have a way to multiply only a certain mobs drops

**Comment by Xavter** [comment]
Yeah it will have to be a slight edit to the current loot multiplier.

**Comment by ttk2** [comment]
no need to edit the default config, we can just run the command and save it.

**Comment by ttk2** [comment]
what are the commands?

**Comment by Xavter** [comment]
Since we already have specific multipliers and (I assume) we're axing the pigmen spawnrate cut in favor of using mustercull, I am going closing the issue after I add a few comments to the code and update the readme...

**Comment by ttk2** [comment]
thanks, sorry for the confusion.

**Comment by jjj5311** [comment]
the commands for mob specific multiplers are 

    humbug loot_multipler <mobname> <multiplier>

**Comment by ttk2** [comment]
Yup. Just waiting on feedback about how much spawning was redacted before I
add the buffs.

**Comment by rourke750** [comment]
bump

**Comment by Xavter** [comment]
Fixed via mustercull
