### ISSUE TITLE
Item ID's Deprecated in 1.8.3 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Humbug#26]
The spawn book is now a spawn emerald, other similarly problematic changes.

**Comment by rourke750** [comment]
Oh fun.  Wonder what else this will mess up.  I should move over citadel to names as well.

**Comment by ttk2** [comment]
Erocs was suggesting we just use a table to translate and keep most of the
current code.

**Comment by rourke750** [comment]
Yea, I was thinking that as well.  Should I add it to namelayer and basically just commit to having all our plugins having a dependency on it or should I try make it separate where I can, like humbug for example?

**Comment by rourke750** [comment]
@erocs

**Comment by erocs** [comment]
Just separate it. Humbug doesn't need a translation layer as it doesn't have DB data. Citadel on the other hand would be best to add a lookup table so all the material IDs remain ints (far less storage, faster queries) but the plugin retrieves the item strings.

**Comment by ttk2** [comment]
So as I add and remove items to my inventory they change.... some plugin must be messing with my inventory and causing interesting things to happen, I think this is specifically the spawn book but that's just a hunch and it remains after I run a /clear to clear my inventory.

**Comment by rourke750** [comment]
So this issue needs to be changed to see how humbug adding in the custom ender pearl stuff affects spawn books and possibly other items.
