### ISSUE TITLE
Allow Admins to open containers even if there is a block above it

### ISSUE THREAD

**Issue by rourke750** [Civcraft/Humbug#58]
@Civcraft/devs Can someone here attempt this.  Please comment so I can assign you.

This is pretty straight forward, just keep looking in the direction we are facing until you hit a chest, cast to chest grab the inv and pop it up for us.

**Comment by Xavter** [comment]
I'll take this one on.

**Comment by rourke750** [comment]
How is this going @Xavter

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/Humbug/commit/8cce6f8c83b00f16c1e1d3023376f748dacf93d7 and https://github.com/Civcraft/Humbug/commit/7b059c7561b72ca4af7022ede9974f2d3aa343bb
