### ISSUE TITLE
drop_ores_as_ore ignores required tools

### ISSUE THREAD

**Issue by TealNerd** [Civcraft/Humbug#77]
Normally ores require a specific tool to mine them but Humbug doesn't check for that so you can mine diamonds with a wooden pick (or even just your hand)

https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1425

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/Humbug/commit/225feaf1db444b93e5ee18fe1a8ca80571795654
