### ISSUE TITLE
Help - Can't disable silktouch behaviour 

### ISSUE THREAD

**Issue by redmag3** [Civcraft/Humbug#81]
I'm not able to find the setting to disable silktouch behaviour, nor a way to disable horse speed replacement.

**Comment by ProgrammerDan** [comment]
Sorry, people like to add features and not document them.

add `horse_speed: 0.0` to disable horse stat rewriting

and `drop_ores_as_ore: false` to disable silktouch behavior

**Comment by ProgrammerDan** [comment]
Actually, just don't use Civcraft's Humbug.

Use devoted's. The `horse_speed` fix I mentioned won't work on Civcraft's, as there is no way to turn it off here. But Devoted's includes the 0.0 as turnoff fix.

**Comment by ProgrammerDan** [comment]
I could patch Civcraft's if you'd rather use this one actually, the fix is minor:

https://github.com/DevotedMC/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L2135

**Comment by redmag3** [comment]
tbh was only downloading off of the civcraft build site because I don't feel confidant compiling them, ty Dan!

**Comment by ProgrammerDan** [comment]
Ok, I'll cherrypick the fix so you get a fresh build.

**Comment by redmag3** [comment]
:D

**Comment by ProgrammerDan** [comment]
Okay, use 1.6.2 once it finishes on the build server.

**Comment by ProgrammerDan** [comment]
Or I pushed to an old repository... andyou should use 1.8.23 when it finishes x.x

**Comment by ProgrammerDan** [comment]
https://build.civcraft.co/job/Humbug-master/ This should be ready for you now.

**Comment by Maxopoly** [comment]
"people like to add features and not document them", the civconfig stuff without an explicit config heavily encourages that :P

I'll admit though that ores as ores (and a few other of my humbug contributions) being undocumented is my fault .

**Comment by ProgrammerDan** [comment]
> "people like to add features and not document them", the civconfig stuff without an explicit config heavily encourages that :P

So true :D
